stages:
  - build
  - test
  - deploy

variables:
  DOCKER_DRIVER: overlay2

before_script:
  - echo "Running before_script"

# Build API
build_api:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker build -t mybackend ./API
  only:
    - main

# Build Frontend
build_frontend:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker build -t myfrontend ./front
  only:
    - main

# Test API
test_api:
  stage: test
  image: mcr.microsoft.com/dotnet/sdk:6.0
  script:
    - cd API
    - dotnet test
  only:
    - main

# Test Frontend
test_frontend:
  stage: test
  image: node:18
  script:
    - cd front
    - npm install
    - npm test
  only:
    - main

# Deploy to Docker Registry
deploy:
  stage: deploy
  image: docker:latest
  services:
    - docker:dind
  script:
    - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_USERNAME" --password-stdin
    - docker tag mybackend $DOCKER_HUB_USERNAME/mybackend:latest
    - docker tag myfrontend $DOCKER_HUB_USERNAME/myfrontend:latest
    - docker push $DOCKER_HUB_USERNAME/mybackend:latest
    - docker push $DOCKER_HUB_USERNAME/myfrontend:latest
  only:
    - main
