# Étape 1 : Utiliser une image légère pour Node.js
FROM node:18-alpine AS build

# Définir le répertoire de travail dans le conteneur
WORKDIR /app

# Copier le package.json et le package-lock.json (si disponible)
COPY package*.json ./

# Installer les dépendances
RUN npm install

# Copier le reste des fichiers de l'application
COPY . .

# Générer la version de production de l'application React
RUN npm run build

# Utiliser une image alpine avec node pour exécuter l'application
FROM node:18-alpine

# Définir le répertoire de travail
WORKDIR /app

# Copier les fichiers build de l'étape précédente
COPY --from=build /app/build /app/build

# Installer 'serve' pour servir les fichiers statiques
RUN npm install -g serve
RUN apk add curl nano
# Exposer le port que ton application va utiliser
EXPOSE 3000

# Lancer l'application avec 'serve'
CMD ["serve", "-s", "build"]